# Generated by Django 6.0 on 2025-12-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_data', models.JSONField()),
                ('extracted_text', models.TextField(blank=True)),
                ('result_summary', models.JSONField()),
                ('brand_name', models.CharField(max_length=200)),
                ('class_type', models.CharField(max_length=200)),
                ('abv', models.CharField(max_length=50)),
                ('net_contents', models.CharField(max_length=50)),
                ('govt_warning', models.BooleanField()),
                ('image', models.ImageField(upload_to='')),
                ('passed', models.BooleanField(default=False)),
            ],
        ),
    ]
