# Generated by Django 6.0 on 2025-12-11 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='result_summary',
        ),
    ]
