# Generated by Django 6.0 on 2025-12-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0002_remove_verification_extracted_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='form_data',
        ),
        migrations.AlterField(
            model_name='verification',
            name='govt_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='verification',
            name='net_contents',
            field=models.CharField(default='', max_length=50),
        ),
    ]
